### ISSUE TITLE
Will you do it for flutter web ?

### ISSUE THREAD

**Issue by catalunha** [a-marenkov/gsheets#32]
Congratulations on the project. Maybe you are already able and you still haven't updated. You can check it out for us and update on the puspec.

**Comment by a-marenkov** [comment]
Hi @catalunha! Oddly it seems to work with flutter web even though pub.dev says otherwise, it's because googleapis_auth  not fully supports it.

Unfortunatly, i can't deliver full flutter web support right now. To do that i need to fork/replace googleapis_auth in gsheets.

If you can do that, PRs are welcome. Thanks.

**Comment by FarsFuad** [comment]
E/flutter ( 6393): [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: RangeError (index): Invalid value: Not in inclusive range 0..42: 43
E/flutter ( 6393): #0      List.[] (dart:core-patch/growable_array.dart:177:60)
E/flutter ( 6393): #1      _SearchState.refreshButton (package:manychatgooglesheet/Screens/AdminScreen/Search.dart:137:27)
E/flutter ( 6393): <asynchronous suspension>
E/flutter ( 6393): #2      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:993:19)
E/flutter ( 6393): #3      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:1111:38)
E/flutter ( 6393): #4      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:183:24)
E/flutter ( 6393): #5      TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:598:11)
E/flutter ( 6393): #6      BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:287:5)
E/flutter ( 6393): #7      BaseTapGestureRecognizer.handlePrimaryPointer (package:flutter/src/gestures/tap.dart:222:7)
E/flutter ( 6393): #8      PrimaryPointerGestureRecognizer.handleEvent (package:flutter/src/gestures/recognizer.dart:476:9)
E/flutter ( 6393): #9      PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:77:12)
E/flutter ( 6393): #10     PointerRouter._dispatchEventToRoutes.<anonymous closure> (package:flutter/src/gestures/pointer_router.dart:122:9)
E/flutter ( 6393): #11     _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:377:8)
E/flutter ( 6393): #12     PointerRouter._dispatchEventToRoutes (package:flutter/src/gestures/pointer_router.dart:120:18)
E/flutter ( 6393): #13     PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:106:7)
E/flutter ( 6393): #14     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:358:19)
E/flutter ( 6393): #15     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:338:22)
E/flutter ( 6393): #16     RendererBinding.dispatchEvent (package:flutter/src/rendering/binding.dart:267:11)
E/flutter ( 6393): #17     GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:295:7)
E/flutter ( 6393): #18     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:240:7)
E/flutter ( 6393): #19     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:213:7)
E/flutter ( 6393): #20     _rootRunUnary (dart:async/zone.dart:1206:13)
E/flutter ( 6393): #21     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
E/flutter ( 6393): #22     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1005:7)
E/flutter ( 6393): #23     _invoke1 (dart:ui/hooks.dart:265:10)
E/flutter ( 6393): #24     _dispatchPointerDataPacket (dart:ui/hooks.dart:174:5)
E/flutter ( 6393): 


this is the error , It says that the rang of colums are 43 , but acculy they are 44

becuse the last colume has an emtpy cells

**Comment by Protoss78** [comment]
Just because I stumpled upon this issue right now - googleapis_auth seems to already support web in its latest version (1.3.1 right now). See https://pub.dev/packages/googleapis_auth for verification.
